<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.weir</groupId>
    <artifactId>weir</artifactId>
    <version>0.1.0-SNAPSHOT</version>
  </parent>
  <artifactId>weir-ds-plugin</artifactId>
  <name>Weir DolphinScheduler Task</name>
  <dependencies>
    <dependency>
      <groupId>io.weir</groupId>
      <artifactId>weir-core</artifactId>
    </dependency>
    <dependency>
      <groupId>io.weir</groupId>
      <artifactId>weir-writer-file</artifactId>
    </dependency>
    <dependency>
      <groupId>io.weir</groupId>
      <artifactId>weir-writer-jdbc</artifactId>
    </dependency>
    <dependency>
      <groupId>io.weir</groupId>
      <artifactId>weir-writer-kafka</artifactId>
    </dependency>
    <dependency>
      <groupId>io.weir</groupId>
      <artifactId>weir-writer-doris</artifactId>
    </dependency>
    <dependency>
      <groupId>io.weir</groupId>
      <artifactId>weir-writer-paimon</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.dolphinscheduler</groupId>
      <artifactId>dolphinscheduler-task-api</artifactId>
      <version>${ds.api.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
    </dependency>
  </dependencies>
  <properties>
    <ds.api.version>3.4.3</ds.api.version>
  </properties>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <artifactSet>
                <excludes>
                  <exclude>org.apache.dolphinscheduler:*</exclude>
                </excludes>
              </artifactSet>
              <transformers>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
              </transformers>
              <createDependencyReducedPom>false</createDependencyReducedPom>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
